/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'businessType' : IDL.Text,
  'requirement' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'submitLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'id' : IDL.Nat })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'businessType' : IDL.Text,
    'requirement' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'submitLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'id' : IDL.Nat })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };